package edu.westminsteru.cmpt355.jasm;

import static edu.westminsteru.cmpt355.jasm.OperandType.*;

public enum Opcode {

    aaload(),
    aastore(),
    aconst_null(),
    aload(Int),
    aload_0(),
    aload_1(),
    aload_2(),
    aload_3(),
    anewarray(ClassName),
    areturn(),
    arraylength(),
    astore(Int),
    astore_0(),
    astore_1(),
    astore_2(),
    astore_3(),
    astore_4(),
    athrow(),
    baload(),
    bastore(),
    bipush(),
    caload(),
    castore(),
    checkcast(),
    d2f(),
    d2i(),
    d2l(),
    dadd(),
    daload(),
    dastore(),
    dcmpg(),
    dcmpl(),
    dconst_0(),
    dconst_1(),
    ddiv(),
    dload(Int),
    dload_0(),
    dload_1(),
    dload_2(),
    dload_3(),
    dmul(),
    dneg(),
    drem(),
    dreturn(),
    dstore(Int),
    dstore_0(),
    dstore_1(),
    dstore_2(),
    dstore_3(),
    dsub(),
    dup(),
    dup_x1(),
    dup_x2(),
    dup2(),
    dup2_x1(),
    dup2_x2(),
    f2d(),
    f2i(),
    f2l(),
    fadd(),
    faload(),
    fastore(),
    fcmpg(),
    fcmpl(),
    fconst_0(),
    fconst_1(),
    fconst_2(),
    fdiv(),
    fload(Int),
    fload_0(),
    fload_1(),
    fload_2(),
    fload_3(),
    fmul(),
    fneg(),
    frem(),
    freturn(),
    fstore(Int),
    fstore_0(),
    fstore_1(),
    fstore_2(),
    fstore_3(),
    fsub(),
    getfield(ClassName, Identifier, Descriptor),
    getstatic(ClassName, Identifier, Descriptor),
    goto_("goto", BranchTarget),
    i2b(),
    i2c(),
    i2d(),
    i2f(),
    i2l(),
    i2s(),
    iadd(),
    iaload(),
    iand(),
    iastore(),
    iconst_0(),
    iconst_1(),
    iconst_2(),
    iconst_3(),
    iconst_4(),
    iconst_5(),
    iconst_m1(),
    idiv(),
    if_acmpeq(BranchTarget),
    if_acmpne(BranchTarget),
    if_icmpeq(BranchTarget),
    if_icmpne(BranchTarget),
    if_icmplt(BranchTarget),
    if_icmpge(BranchTarget),
    if_icmpgt(BranchTarget),
    if_icmple(BranchTarget),
    ifeq(BranchTarget),
    ifne(BranchTarget),
    iflt(BranchTarget),
    ifge(BranchTarget),
    ifgt(BranchTarget),
    ifle(BranchTarget),
    ifnonnull(BranchTarget),
    ifnull(BranchTarget),
    iinc(Int, Int),
    iload(Int),
    iload_0(),
    iload_1(),
    iload_2(),
    iload_3(),
    imul(),
    ineg(),
    instanceOf(ClassName),
    // invokedynamic
    invokeinterface(ClassName, Identifier, MethodDescriptor),
    invokespecial(ClassName, Identifier, MethodDescriptor),
    invokestatic(ClassName, Identifier, MethodDescriptor),
    invokevirtual(ClassName, Identifier, MethodDescriptor),
    ior(),
    irem(),
    ireturn(),
    ishl(),
    ishr(),
    istore(Int),
    istore_0(),
    istore_1(),
    istore_2(),
    istore_3(),
    isub(),
    iushr(),
    ixor(),
    // jsr
    l2d(),
    l2f(),
    l2i(),
    ladd(),
    laload(),
    land(),
    lastore(),
    lcmp(),
    lconst_0(),
    lconst_1(),
    ldc__Int("ldc", Int),
    ldc__Float("ldc", Float),
    ldc__String("ldc", String),
    // ldc variants for class type, method type, method handle
    ldc2__Long("ldc2", Long),
    ldc2__Double("ldc2", Double),
    ldiv(),
    lload(Int),
    lload_0(),
    lload_1(),
    lload_2(),
    lload_3(),
    lmul(),
    lneg(),
    // lookupswitch
    lor(),
    lrem(),
    lreturn(),
    lshl,
    lshr,
    lstore(Int),
    lstore_0(),
    lstore_1(),
    lstore_2(),
    lstore_3(),
    lsub,
    lushr,
    lxor,
    monitorenter,
    monitorexit,
    multianewarray(ClassName, Int),
    new_("new", ClassName),
    newarray(ArrayType),
    nop,
    pop,
    pop2,
    putfield(ClassName, Identifier, Descriptor),
    putstatic(ClassName, Identifier, Descriptor),
    // ret
    return_("return"),
    saload(),
    sastore(),
    sipush(Int),
    swap();
    // tableswitch
    // wide

    private String name;
    private OperandType[] operands;

    Opcode(String name, OperandType... operands) {
        this.name = super.name();
        this.operands = operands;
    }
    
    Opcode(OperandType... operands) {
        this.name = super.name();
        this.operands = operands;
    }
}
